package com.shivamkumarjha.supaflix.model.app

object GenreList {
    private val genres: ArrayList<Genre> = arrayListOf()

    val actionGenre = Genre("J7HHcRU7", "action")
    val adventureGenre = Genre("BOhohUUh", "adventure")
    val animationGenre = Genre("I8UxM9cV", "animation")
    val biographyGenre = Genre("DxtYHrRQ", "biography")
    val costumeGenre = Genre("Ooy47EnD", "costume")
    val comedyGenre = Genre("wnq50Wt2", "comedy")
    val crimeGenre = Genre("8gT29yYO", "crime")
    val documentaryGenre = Genre("jrgZDu4c", "documentary")
    val familyGenre = Genre("02R3oJj7", "family")
    val fantasyGenre = Genre("DVTJoVmF", "fantasy")
    val gameShowGenre = Genre("lwxxvXvm", "game-show")
    val historyGenre = Genre("i5IGpR5x", "history")
    val horrorGenre = Genre("JQJPb64x", "horror")
    val kungfuGenre = Genre("t8FZTE2E", "kungfu")
    val musicGenre = Genre("iVs02T2f", "music")
    val mysteryGenre = Genre("4dRk5f6B", "mystery")
    val realityTvGenre = Genre("fEbGIjFI", "reality-tv")
    val romanceGenre = Genre("Fe2rfiBq", "romance")
    val sciFiGenre = Genre("D1NvOmlA", "sci-fi")
    val sportGenre = Genre("6nM1oJXH", "sport")
    val thrillerGenre = Genre("AIKQberR", "thriller")
    val tvShowGenre = Genre("7fBKjHmk", "tv-show")
    val warGenre = Genre("flBwy9lF", "war")
    val westernGenre = Genre("sYITdTAG", "western")

    fun getAllGenres(): ArrayList<Genre> {
        genres.clear()
        genres.add(actionGenre)
        genres.add(adventureGenre)
        genres.add(animationGenre)
        genres.add(biographyGenre)
        genres.add(costumeGenre)
        genres.add(comedyGenre)
        genres.add(crimeGenre)
        genres.add(documentaryGenre)
        genres.add(familyGenre)
        genres.add(fantasyGenre)
        genres.add(gameShowGenre)
        genres.add(historyGenre)
        genres.add(horrorGenre)
        genres.add(kungfuGenre)
        genres.add(musicGenre)
        genres.add(mysteryGenre)
        genres.add(realityTvGenre)
        genres.add(romanceGenre)
        genres.add(sciFiGenre)
        genres.add(sportGenre)
        genres.add(thrillerGenre)
        genres.add(tvShowGenre)
        genres.add(warGenre)
        genres.add(westernGenre)
        return genres
    }
}